spring:
  datasource:
    # opengauss数据库配置
    driver-class-name: org.opengauss.Driver
    url: jdbc:opengauss://110.41.126.115:8000/CQU_DB2021
    username: db_user2021_276
    password: db_user@123
knife4j:
  enable: true
  # 开启Swagger的Basic认证功能
  basic:
    enable: true
    # Basic认证用户名
    username: admin
    # Basic认证密码
    password: admin